### ISSUE TITLE
Name of device not showing

### ISSUE THREAD

**Issue by ekokurniadi** [rohitsangwan01/win_ble#12]
Name of discovered device not show

**Comment by alexcode9** [comment]
Please give more details.
This issue has not been reported before, it might be related to your code.

**Comment by yusmi25** [comment]
same problem, I'm using example code
name device not showing, but rssi and address showing

**Comment by alexcode9** [comment]
Scan results in win_ble are pretty much what you get from low level interface and can return no name but if you look at logs you should see the names... Since in the example devices are added but not updated you get the first scan that usually doesn't contain the namen, to fix that change [these lines](https://github.com/rohitsangwan01/win_ble/blob/018336ccfea577b18ca637093998349513fad24c/example/lib/main.dart#L35-L42) into this:
```
// Listen to Scan Stream , we can cancel in onDispose()
scanStream = WinBle.scanStream.listen((event) {
  setState(() {
    final index = devices.indexWhere((element) => element.address == event.address);
    if (index != -1) {
      devices[index] = event;
    } else {
      devices.add(event);
    }
  });
});
```

If you want to improve it more you could cache names and continue to update other data

**Comment by rohitsangwan01** [comment]
@ekokurniadi @yusmi25 few Ble devices does not shows name or advertising with empty name , you can cross check with NrfConnect mobile App
let me know if  you are getting name of that device in NrfConnect app but not in win_ble

**Comment by chuanlingZhao** [comment]
same problem, I'm using example code
name device not showing, but rssi and address showing
and  I can not see names in logs, there hasn't been any change, still no name visible after fix that change

**Comment by chuanlingZhao** [comment]
![image](https://github.com/rohitsangwan01/win_ble/assets/85494339/57234c7c-4528-4b84-a25e-da9b34327edc)
![image](https://github.com/rohitsangwan01/win_ble/assets/85494339/3ad0b1ab-b935-46aa-aa01-00c8b9b7eb07)
This is my logs and the modified content

**Comment by rohitsangwan01** [comment]
> This is my logs and the modified content

@chuanlingZhao seems like this device does not advertise name
Can you cross check with nrfConnect mobile application

**Comment by chuanlingZhao** [comment]
Okay, I'll try try

**Comment by BikeBr0** [comment]
I've been running into the same problem. I don't think the bug is fixed, but I can provide some, hopfully, relevant insights. In my case, I added a where clause to my `WinBle.scanStream` and filtered out BleDevices that did not contain a specific serviceUuid. It appears that the serviceUuids list is empty when the localName contains data and vice versa.

This was not intuitive having worked with other Bluetooth Stacks on Flutter. It might be a good design change to build the data up for each BleDevice and add more comprehensive data to the stream. In the menatime, I think I can work with this.

**Comment by rohitsangwan01** [comment]
@BikeBr0 can you cross check with other apps like NRF, if you are getting same behaviour while scanning

**Comment by BikeBr0** [comment]
Yes, the device name appears in nrfConnect.

**Comment by rohitsangwan01** [comment]
@BikeBr0 are you using NrfConnect on Desktop or Mobile ?
not sure if desktop has this issue, or this library 
[Here](https://github.com/rohitsangwan01/win_ble/blob/main/BLEServer/BLEServer/BLEServer.cpp#L663C27-L678) is the logic to handle bluetooth discovered devices

**Comment by BikeBr0** [comment]
I was testing nrfConnect on Android. I'll review the logic to handle Bluetooth discovered objects tomorrow.

**Comment by BikeBr0** [comment]
I just checked with nRFConnect for Windows Desktop. My peripheral's full response is displayed in the UI (Name, Services, Flags, Manufacturer Data). I assume it is collating the various incoming packets.

**Comment by BikeBr0** [comment]
Here's a summary of the problem I was facing, which resulted in the BleDevice name not always being available.

BLE packets are returned in multiple stuctures. Some with a localName but no manufacturerData nor serviceUuids and some with manufacturerData and serviceUuids but no localName. This is a log filtered on a specific MAC Address:

`flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -63, timestamp: 24984276796948.953, advType: ConnectableUndirected, localName: 2ND AVE SB, adStructures: [{type: 1, data: [6]}, {type: 9, data: [50, 78, 68, 32, 65, 86, 69, 32, 83, 66]}], serviceUuids: []}
flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -63, timestamp: 24984276796950.098, advType: ScanResponse, localName: , manufacturerData: [227, 2, 2], adStructures: [{type: 7, data: [124, 22, 165, 94, 186, 17, 203, 146, 12, 73, 127, 184, 1, 17, 154, 86]}, {type: 255, data: [227, 2, 2]}], serviceUuids: [{569a1101-b87f-490c-92cb-11ba5ea5167c}]}
flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -77, timestamp: 24984276797153.934, advType: ConnectableUndirected, localName: 2ND AVE SB, adStructures: [{type: 1, data: [6]}, {type: 9, data: [50, 78, 68, 32, 65, 86, 69, 32, 83, 66]}], serviceUuids: []}
flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -77, timestamp: 24984276797154.906, advType: ScanResponse, localName: , manufacturerData: [227, 2, 2], adStructures: [{type: 7, data: [124, 22, 165, 94, 186, 17, 203, 146, 12, 73, 127, 184, 1, 17, 154, 86]}, {type: 255, data: [227, 2, 2]}], serviceUuids: [{569a1101-b87f-490c-92cb-11ba5ea5167c}]}
flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -77, timestamp: 24984276797888.477, advType: ConnectableUndirected, localName: 2ND AVE SB, adStructures: [{type: 1, data: [6]}, {type: 9, data: [50, 78, 68, 32, 65, 86, 69, 32, 83, 66]}], serviceUuids: []}
flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -77, timestamp: 24984276797889.496, advType: ScanResponse, localName: , manufacturerData: [227, 2, 2], adStructures: [{type: 7, data: [124, 22, 165, 94, 186, 17, 203, 146, 12, 73, 127, 184, 1, 17, 154, 86]}, {type: 255, data: [227, 2, 2]}], serviceUuids: [{569a1101-b87f-490c-92cb-11ba5ea5167c}]}
flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -61, timestamp: 24984276797988.273, advType: ConnectableUndirected, localName: 2ND AVE SB, adStructures: [{type: 1, data: [6]}, {type: 9, data: [50, 78, 68, 32, 65, 86, 69, 32, 83, 66]}], serviceUuids: []}
flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -63, timestamp: 24984276797989.32, advType: ScanResponse, localName: , manufacturerData: [227, 2, 2], adStructures: [{type: 7, data: [124, 22, 165, 94, 186, 17, 203, 146, 12, 73, 127, 184, 1, 17, 154, 86]}, {type: 255, data: [227, 2, 2]}], serviceUuids: [{569a1101-b87f-490c-92cb-11ba5ea5167c}]}
flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -78, timestamp: 24984276798925.355, advType: ConnectableUndirected, localName: 2ND AVE SB, adStructures: [{type: 1, data: [6]}, {type: 9, data: [50, 78, 68, 32, 65, 86, 69, 32, 83, 66]}], serviceUuids: []}
flutter: Received Message : {_type: scanResult, bluetoothAddress: 00:16:a4:76:fa:d8, rssi: -78, timestamp: 24984276798925.82, advType: ScanResponse, localName: , manufacturerData: [227, 2, 2], adStructures: [{type: 7, data: [124, 22, 165, 94, 186, 17, 203, 146, 12, 73, 127, 184, 1, 17, 154, 86]}, {type: 255, data: [227, 2, 2]}], serviceUuids: [{569a1101-b87f-490c-92cb-11ba5ea5167c}]}`

I received a total of 10 packets of 2 different types. Only half of the packets contained a localName. This isn't a problem but was unexpected and prevented me from filtering on ManafacturerData or serviceUuids. Instead, I had to first collate all the incoming packets by MAC Address, build up the full response, and then filter the stream. Other Flutter BLE libraries (for mobile) seem to handle the collation of related packets so other developers might hit this stumbling block too.

**Comment by abusaadp** [comment]
Why is this issue closed? Even I am not able to see the name of the bluetooth device in my windows laptop when I scan for the bluetooth devices.

**Comment by BikeBr0** [comment]
@abusaadp, is the name never available in the packets? For me, only 50% of the packets contained the name. If the name is never available then perhaps you have an issue with the peripheral?

**Comment by abusaadp** [comment]
I am having my phone nearby and its name is not showing up in the scanned devices in the app. The name of the phone is showing up in the bluetooth scanned devices of windows system but not in the app. What do you mean by issue with the peripheral?

**Comment by BikeBr0** [comment]
Your phone is the peripheral in this case. (But confirm your phone is in fact advertising through BLE and not Bluetooth Classic). Does it show up in nRFConnect?

If this checks out you can perform a scan and log each packet as it comes in, you should see some of the packets have the phones name.

**Comment by abusaadp** [comment]
It doesn't show up in nRFConnect. There are no devices shown in nRFConnect. But our app shows a list of devices. I am not sure which one of those devices is my phone as the name shown is N/A. How to confirm my phone is advertising through BLE and not Bluetooth Classic.
Is there any Bluetooth Classic plugin in Flutter for windows so that I can check if my phone shows up there. I am trying to initiate bluetooth calling from Windows PC to Android/iOS phone using flutter.

**Comment by rohitsangwan01** [comment]
@BikeBr0 to verify your phone, make sure your phone is advertising in ble peripheral mode, you can try out my another library [ble_peripheral](https://pub.dev/packages/ble_peripheral) for this,
and to check devices, you can filter by manufacturer data or primary services

**Comment by Giovanni-Fantin** [comment]
I have the same problem. With flutter reactive ble (another ble library for flutter that works on iOs/android) on mobile i can see the name of the ble device 'xy', and also with nfr connect, but with Win Ble l can't. 
![Screenshot 2024-06-04 101706](https://github.com/rohitsangwan01/win_ble/assets/157793627/70ae0382-69e3-4e83-9eca-4a3fd76cb036)

Also with the example app as you can see

**Comment by chandlery54** [comment]
> I've been running into the same problem. I don't think the bug is fixed, but I can provide some, hopefully, relevant insights. In my case, I added a where clause to my `WinBle.scanStream` and filtered out BleDevices that did not contain a specific serviceUuid. It appears that the serviceUuids list is empty when the localName contains data and vice versa.
> 
> This was not intuitive having worked with other Bluetooth Stacks on Flutter. It might be a good design change to build the data up for each BleDevice and add more comprehensive data to the stream. In the menatime, I think I can work with this.

This is exactly what we are experiencing too. 
We saw the same behavior and are able to work around it by checking for _either_ a known name _or_ serviceUuid, but they never come in together. We then have to make sure to fill in our cached name or serviceUuid when we see the device again with one or the other but never both.

**Comment by rohitsangwan01** [comment]
> This is exactly what we are experiencing too. We saw the same behavior and are able to work around it by checking for _either_ a known name _or_ serviceUuid, but they never come in together. We then have to make sure to fill in our cached name or serviceUuid when we see the device again with one or the other but never both.

The name might be in extra data, and on windows a device might be caught in two kind of advertisements
One with main data and connectable
Second with the extra data
So i think its good option to cache results and combine both to get proper result
