### ISSUE TITLE
stream connectionStream empty results

### ISSUE THREAD

**Issue by yusmi25** [rohitsangwan01/win_ble#14]
I'm using this code in initState to get connectionStream but empty result
`
void initState() {
    super.initState();
   connectionEvent = WinBle.connectionStream.listen((event) {
      print("Bluetooth Event : $event");
    });
}
`
any Solution, Thanks

**Comment by rohitsangwan01** [comment]
@yusmi25 you have to connect to a device , then this stream will return Connection Events of that device 
and if you want to get connection Event of a particular device only , then use 
```dart
 WinBle.connectionStreamOf(device.address)
```

**Comment by yusmi25** [comment]
thanks, it's works :D
