### ISSUE TITLE
no metheod to get the initial Ble statue,is on or off

### ISSUE THREAD

**Issue by NickYoung-max** [rohitsangwan01/win_ble#18]

**Comment by rohitsangwan01** [comment]
@NickYoung-max can you try with the bleState stream , is it giving you the current state on subscribing , or only when you change status after subscribing

**Comment by NickYoung-max** [comment]
> 

yeah,if the system bluetooth is off,it should not do anything. I'm going to use this feature in this version of my code,can you c add this feature as soon as possible?Thanks!

**Comment by rohitsangwan01** [comment]
@NickYoung-max added in 1.0.1
