### ISSUE TITLE
support multiple platforms

### ISSUE THREAD

**Issue by ekuleshov** [rohitsangwan01/win_ble#2]
It is great to see BLE support for windows!

Though I'm wondering if this could be incorporated with other BLE plugins to support multiple platforms:

* https://pub.dev/packages/flutter_blue_plus
* https://pub.dev/packages/flutter_reactive_ble

The former is probably easier to integrate with, but it hasn't been refactored to support federated plugins yet.

On a side note, I wonder if win32 BLE support could be built on top of the Dart bindings for win32. E.g. https://pub.dev/packages/win32 already has bunch of BLE API mapped.

**Comment by rohitsangwan01** [comment]
@ekuleshov thanks man ,sure i can try to create a PR on these plugins when i will have time ,
and i already tried win32 for Ble and it was not working fine , so till its not stable , we can use this native c++ implementation
