### ISSUE TITLE
CharacteristicValueStream not working correctly!

### ISSUE THREAD

**Issue by kolan51** [rohitsangwan01/win_ble#21]
When I am provisioning a BLE device the data from CharacteristicValueStream is ok. Also the data from Mesh Beacon is received correctly. Further commands to a ble device just return the Mesh Beacon back from the device in a weird manner, for instance:

This is a mesh beacon package: 01010042c21ace623f50b0000000005f9ef9d254274626 (0101 start means a mesh beacon packet)

After sending a config node reset command to the device (Command works): 41010042c21ace623f50b0000000005f9ef9d254 + c1274626 is received wchihs is the same as before just the 4 and c1 are different.
 
We need a fix for our project, please help us.

**Comment by rohitsangwan01** [comment]
@kolan51 please try with this PR https://github.com/rohitsangwan01/win_ble/pull/22

**Comment by rohitsangwan01** [comment]
@kolan51 released new version, please check if working fine now
