### ISSUE TITLE
Running the Example on Windows

### ISSUE THREAD

**Issue by DeVeraGiovanni** [rohitsangwan01/win_ble#23]
### I'm trying to run the example of win_ble, but I'm encountering an error. Do you have any ideas on how to fix these issues?

`Launching lib\main.dart on Windows in debug mode...
main.dart:1
windows/runner/Runner.rc does not define use Flutter version information, updating.
../../../AppData/Local/Pub/Cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart(15,16): error GE5CFE876: The method 'File.create' has fewer named arguments than those of overridden method 'File.create'. [C:\Users\Gvnn\Downloads\win_ble-main\example\build\windows\flutter\flutter_assemble.vcxproj]
file.dart:1
../../../AppData/Local/Pub/Cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart(15,16): error GE5CFE876: The method 'File.create' doesn't have the named parameter 'exclusive' of overridden method 'File.create'. [C:\Users\Gvnn\Downloads\win_ble-main\example\build\windows\flutter\flutter_assemble.vcxproj]
file.dart:1
../../../AppData/Local/Pub/Cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart(22,8): error GE5CFE876: The method 'ForwardingFile.createSync' has fewer named arguments than those of overridden method 'File.createSync'. [C:\Users\Gvnn\Downloads\win_ble-main\example\build\windows\flutter\flutter_assemble.vcxproj]
forwarding_file.dart:1
../../../AppData/Local/Pub/Cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart(22,8): error GE5CFE876: The method 'ForwardingFile.createSync' doesn't have the named parameter 'exclusive' of overridden method 'File.createSync'. [C:\Users\Gvnn\Downloads\win_ble-main\example\build\windows\flutter\flutter_assemble.vcxproj]
forwarding_file.dart:1

C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\Users\Gvnn\Downloads\win_ble-main\example\build\windows\CMakeFiles\eeb9815d2e7458b62883e976ef6f0eaf\flutter_windows.dll.rule;C:\Users\Gvnn\Downloads\win_ble-main\example\build\windows\CMakeFiles\42ab1f30e2252f3b7d78c1878a12bdb4\flutter_assemble.rule;C:\Users\Gvnn\Downloads\win_ble-main\example\windows\flutter\CMakeLists.txt' exited with code 1. [C:\Users\Gvnn\Downloads\win_ble-main\example\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
Exited (sigterm)`

![image](https://github.com/rohitsangwan01/win_ble/assets/53848311/51d88e5a-276d-4c60-82d6-4872c110ecdb)

**Comment by rohitsangwan01** [comment]
@DeVeraGiovanni are you on latest flutter version, if yes please also try to run `dart pub upgrade` once, and try again

**Comment by DeVeraGiovanni** [comment]
Hello @rohitsangwan01, my Flutter version is 3.10.6, stable channel. Running dart pub upgrade resolved the error. Thank you!
