### ISSUE TITLE
[Windows] Can't turn on the bluetooth on Example 

### ISSUE THREAD

**Issue by DeVeraGiovanni** [rohitsangwan01/win_ble#25]
### How can I troubleshoot issues with enabling Bluetooth? I'm currently using win_ble: ^1.0.1. Additionally, when I attempt to activate Bluetooth manually through the settings, the state doesn't reflect the change in the desktop app.

Here is a sample video:

https://github.com/rohitsangwan01/win_ble/assets/53848311/dd8962fe-4907-4953-a7f5-f1c3fc82d082

**Comment by rohitsangwan01** [comment]
Seems like BLEServer is not running, please try to run example_dart from repo, and share the logs

**Comment by DeVeraGiovanni** [comment]
I tried running the example_dart and it is working.

Here is the video:

https://github.com/rohitsangwan01/win_ble/assets/53848311/5054256d-04a5-44bc-a28e-96ee7605675c

**Comment by DeVeraGiovanni** [comment]
UPDATE: I copy the serverPath in the example_dart and change the initialize() to 

`
String serverPath = "..\\lib\\assets\\BLEServer.exe";
  
void initialize() async {
    await WinBle.initialize(
      serverPath: serverPath,
      enableLog: true,
    );
  }
` 
and now it is working.


https://github.com/rohitsangwan01/win_ble/assets/53848311/311c52d8-98fd-49ab-b4a1-63da8a0393be

**Comment by rohitsangwan01** [comment]
> UPDATE: I copy the serverPath in the example_dart and change the initialize() to

@DeVeraGiovanni copy where? 
to flutter app, in flutter app we should use ` await WinServer.path` for getting server path, isn't it working for you ?

**Comment by DeVeraGiovanni** [comment]
the path output for me is C:\Users\Gvnn\AppData\Local\Temp/file_01.tmp

**Comment by rohitsangwan01** [comment]
> the path output for me is C:\Users\Gvnn\AppData\Local\Temp/file_01.tmp

can you cross check if BleServer (file_01.tmp) file stored in this path ?
if yes, please try to modify code little bit, from [here](https://github.com/rohitsangwan01/win_ble/blob/main/lib/win_file.dart#L21) replace, file_01.tmp with BLEServer.exe

**Comment by DeVeraGiovanni** [comment]
file_01.tmp is stored 
![image](https://github.com/rohitsangwan01/win_ble/assets/53848311/0263916c-cd35-45db-98d4-079fb6292d4c)

after modifying 
var filePath = tempPath + '/file_01.tmp';
to
![image](https://github.com/rohitsangwan01/win_ble/assets/53848311/8851eb03-df5e-484e-9ba0-02891b8c5c6f)

here is my new path:
C:\Users\Gvnn\AppData\Local\Temp/BLEServer.exe

but I still can't turn on the bluetooth

![image](https://github.com/rohitsangwan01/win_ble/assets/53848311/6c5e3845-4304-4377-96d3-ee95217847e8)

**Comment by rohitsangwan01** [comment]
@DeVeraGiovanni are you getting any logs related to this ?

**Comment by DeVeraGiovanni** [comment]
I tried to open the 
\win_ble-main\win_ble-main\example\build\windows\runner\Debug\win_ble_example.exe 
and it shows this error
![image](https://github.com/rohitsangwan01/win_ble/assets/53848311/b1044738-d80f-4fdc-bfb1-31b629bef3bd)

**Comment by rohitsangwan01** [comment]
ok seems like that issue with the path of bleServer.exe, not sure if its with your system path , or plugin's issue
can you try in another pc, just to test

**Comment by rohitsangwan01** [comment]
> After testing win_ble on another PC, it functions perfectly. It appears that the issue lies within my own system.

Ok whats your windows version ?
And copy the path of BleServer file which created by Flutter 
And use that path in example_dart
If not worked then try to modify the path 
Like replace `/` with `\\`

**Comment by DeVeraGiovanni** [comment]
Currently, my temporary solution is upgrading from Windows 10 to Windows 11. While this has resolved the blestate issue, I still encounter a problem with scanning for other Bluetooth devices. It appears that the issue lies with my PC rather than the win_ble. It's possible that there is an underlying problem with my computer. For now, I'll be focusing on troubleshooting since the other PC can scan for other Bluetooth devices.

![image](https://github.com/rohitsangwan01/win_ble/assets/53848311/12fae86d-84c6-428a-a7d6-e6ceaf0c9cc9)

**Comment by rohitsangwan01** [comment]
@DeVeraGiovanni Maybe something with your ble adapter, cross check with other apps like Nrf Desktop or Light Blue

**Comment by DeVeraGiovanni** [comment]
Thanks, @rohitsangwan01. I will conduct further research on Nrf Desktop or Light Blue.
