### ISSUE TITLE
Disconnecting after clicking Subscribe Characteristics

### ISSUE THREAD

**Issue by DeVeraGiovanni** [rohitsangwan01/win_ble#26]
Trying to use the example of win_ble but after clicking the subscribe characteristics it will show an error:

`flutter: Received Message : {_type: response, _id: 3, error: Unspecified error
Requested characteristic not found}
flutter: ADDRESS: b0:d2:78:4b:ab:c1
flutter: SERVICE ID: 0000FFE0-0000-1000-8000-00805F9B34FB
flutter: CHAR ID: 0000FFE1-0000-1000-8000-00805F9B34FB
flutter: Received Message : {_type: disconnectEvent, device: BluetoothLE#BluetoothLE00:93:37:26:b1:3b-b0:d2:78:4b:ab:c1}
flutter: Connection Event : {device: b0:d2:78:4b:ab:c1, connected: false}
flutter: Received Message : {_type: disconnectEvent, device: BluetoothLE#BluetoothLE00:93:37:26:b1:3b-b0:d2:78:4b:ab:c1}`

**Comment by rohitsangwan01** [comment]
@DeVeraGiovanni like mentioned in the error : `error: Unspecified error Requested characteristic not found`
make sure the characteristic is correct, and exists
i would suggest, first fetch all the characteristics and then use them

**Comment by DeVeraGiovanni** [comment]
Hi sorry for the late reply. I finally fixed it but my next problem is the data lost. If i send "This is a long message" the app only capture the "ge". See the video below. Is there any way I can fix this?

I'm using HM-10 Bluetooth Module


https://github.com/rohitsangwan01/win_ble/assets/53848311/77fcaeb7-2457-45c7-8504-1b3ad62abff0

**Comment by rohitsangwan01** [comment]
@DeVeraGiovanni please share the Logs, when you send this long message
seems like you are getting the long message but in parts, and in app only last part is visible , i.e: 'ge'

**Comment by DeVeraGiovanni** [comment]
Hello when i type the "This is a long message" this is what I got from subscribe characteristics

```
flutter: Received Message : {_type: response, _id: 6, result: 1}
flutter: Received Message : {_type: valueChangedNotification, subscriptionId: 1, value: [84, 104, 105, 115, 32, 105, 115, 32, 97, 32, 108, 111, 110, 103, 32, 109, 101, 115, 115, 97]}
flutter: Received Message : {_type: valueChangedNotification, subscriptionId: 1, value: [103, 101, 13, 10]}
flutter: CharValue : {address: b0:d2:78:4b:ab:c1, serviceId: 0000ffe0-0000-1000-8000-00805f9b34fb, characteristicId: 0000ffe1-0000-1000-8000-00805f9b34fb, value: [84, 104, 105, 115, 32, 105, 115, 32, 97, 32, 108, 111, 110, 103, 32, 109, 101, 115, 115, 97]}
flutter: CharValue : {address: b0:d2:78:4b:ab:c1, serviceId: 0000ffe0-0000-1000-8000-00805f9b34fb, characteristicId: 0000ffe1-0000-1000-8000-00805f9b34fb, value: [103, 101, 13, 10]}
flutter: Received Message : {_type: response, _id: 7, result: [103, 101, 13, 10]}
flutter: ge
```

**Comment by DeVeraGiovanni** [comment]
Thanks, @rohitsangwan01. I tested it with another message, and it appears there is a 20-character limit. I'll merge the result just like you suggested. Thank you for your assistance once more.
