### ISSUE TITLE
The Object has been closed error coming after desconnected by turning ble device off and on again

### ISSUE THREAD

**Issue by abdussalammahmood1** [rohitsangwan01/win_ble#27]
To reproduce : 
1) Scan and connect to a ble device 
2) Power off the ble device to disconnect
3) Now power on the ble device 
4) Connect device again while staying on same page  as step 1
5) now try to write / read or subsribe anything . It says "The Object has been closed ".

Although if I disconnect and reconnect 1 more time it starts to work fine .

**Comment by abdussalammahmood1** [comment]
Yes

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lunxinfeng** [comment]
I have same issue

**Comment by rohitsangwan01** [comment]
> rescan and connect, throw error

@lunxinfeng what error you got when try to connect again after auto disconnect ?
Also are you sure that device is getting discovered in scanResults, and only after appearing in scanResults you are connecting to it

**Comment by lunxinfeng** [comment]
> > rescan and connect, throw error
> 
> @lunxinfeng what error you got when try to connect again after auto disconnect ? Also are you sure that device is getting discovered in scanResults, and only after appearing in scanResults you are connecting to it

sorry, I found the problem, I not called unSubscribeFromCharacteristic when power off ble device.  now it worked fine. Thank you!

1. connect
2. discoverServices
3. discoverCharacteristics
4. subscribeToCharacteristic

**Comment by rohitsangwan01** [comment]
> sorry, I found the problem, I not called unSubscribeFromCharacteristic when power off ble device. now it worked fine. Thank you!
> 
> 1. connect
> 2. discoverServices
> 3. discoverCharacteristics
> 4. subscribeToCharacteristic

Great, @abdussalammahmood1 i think you can also try this fix , am closing this for now, you can open again if this solution is not working for you

**Comment by BikeBr0** [comment]
Is this fix available in the 1.0.1 version on pub.dev?

**Comment by BikeBr0** [comment]
I am experiencing the same bug but calling WinBle.unSubscribeFromCharacteristic does not solve the issue. Here are my steps to reproduce:

1. Scan for peripheral
2. Connect and write to peripheral
3. Power down peripheral
    a. WinBle.connectionStream handler detects disconnected event and my code calls WinBle.unSubscribeFromCharacteristic
    b. The following error is logged: ```The object has been closed.
      
      The object has been closed.```
4. Power up peripheral
5. Scan again
6. Connect and attempt to write to peripheral
    a.  The following error is logged again: ```The object has been closed.
      
      The object has been closed.```
7. Disconnect from peripheral (through flutter)
8. Connect and write
9. Write succeeds with no error
