### ISSUE TITLE
[ERROR] | 9:59:24 647ms | connectToDice:Unspecified error

### ISSUE THREAD

**Issue by Snofkin** [rohitsangwan01/win_ble#28]
I want to connect the BLE device with the address but i am getting this issue even though the device is available

Device not found (null)}
flutter: Received Message : {_type: response, _id: 1, error: Unspecified error

**Comment by rohitsangwan01** [comment]
@Snofkin you can connect to the ble devce, only if that device is discovered in ScannedDevices list
so before connecting , wait for that device to appear in scannedDevices list

**Comment by Snofkin** [comment]
Okay Thanks... Is there any possibility that we can connect with only device id like in flutter_blue_plus at a moment?

**Comment by rohitsangwan01** [comment]
@Snofkin not yet, but you can create your own method something like


connect( ADDRESS) ->.  AutoStartScanning-> FoundDeviceWithThisAddress -> StopScanning and Connect, put some timeout as well if you want to,make sure to stop scanning before Connecting

**Comment by amirsuwal01** [comment]
Okay.. Thanks
