### ISSUE TITLE
Temp/file_01.tmp problem

### ISSUE THREAD

**Issue by KatayR** [rohitsangwan01/win_ble#34]
In scanning screen when I connect to a device, push to another page, "lose connection"(not manually disconnect), detect it via  "connectionStreamOf" push back(or pop)to scanning screen I get this error. Actually, many scenarios leads to this error. 

Restarting the app (manually or programatically) solves the problem.

`
Unhandled Exception: PathAccessException: Cannot open file, path = 'C:\Users\xyzuser\AppData\Local\Temp/file_01.tmp' (OS Error: The process cannot access the file because it is being used by another process.`

**Comment by rohitsangwan01** [comment]
> ` Unhandled Exception: PathAccessException: Cannot open file, path = 'C:\Users\xyzuser\AppData\Local\Temp/file_01.tmp' (OS Error: The process cannot access the file because it is being used by another process.`

are you on older version ? 
new version of library have ble_server.exe instead of file_01.tmp

**Comment by KatayR** [comment]
I think I'm on 1.0.1

**Comment by rohitsangwan01** [comment]
> I think I'm on 1.0.1

please try with 1.0.2
