### ISSUE TITLE
Change in `path` api does not follow semantic versioning guidelines. 

### ISSUE THREAD

**Issue by wxxedu** [rohitsangwan01/win_ble#36]
Firstly, thanks so much for creating this package. 

As described, the change of `path` from a getter to a function does not follow semantic versioning guidelines (should bump a major version). This will cause confusion in the users, as dart will load the latest version that's compatible with the version specified, but that will cause error in the code when you try to compile and run it. 

Because this took me a while to find out and the code linter would essentially not give any help with that regard (but the code does not run), I think it may be best if this could be made into a breaking change next time :-). 

Thanks again for the package!

**Comment by rohitsangwan01** [comment]
@wxxedu sure, my bad, i will make sure to bump major version with breaking change next time
