### ISSUE TITLE
Issue with startScanning()

### ISSUE THREAD

**Issue by Giovanni-Fantin** [rohitsangwan01/win_ble#39]
When calling the Bluetooth scanning method (startScanning();) in the initState of a widget, the scanning process does not start. However, when associated with a button press (for example an IconButton), scanning works as expected. Maybe i'm doing something wrong, i'm new in flutter coding. If it works for you, please tell me, i will close this issue and retry to do it

**Comment by rohitsangwan01** [comment]
@Gionni997 are you waiting for initialisation before starting scan

**Comment by Giovanni-Fantin** [comment]
@rohitsangwan01 thank you very much for the reply. If I use this function: Future.delayed(const Duration(seconds: 1), () {startScanning();}); it works. But i would like to do it without using it.

**Comment by rohitsangwan01** [comment]
@Gionni997 you have to use await with

await WinBle.initialize…

Only then you can call StartScanning

**Comment by Giovanni-Fantin** [comment]
I had initialized it, the problem was another but i've solved it. Thank you for your work

**Comment by Giovanni-Fantin** [comment]
I've modified this part (that also worked today but not yesterday😁  ): 

    bleStateStream = WinBle.bleState.listen((BleState state) {
      setState(() {
        bleState = state;
      });
    });
    Future.delayed(const Duration(seconds: 1), () {startScanning();});
      super.initState();
With this: 

bleStateStream = WinBle.bleState.listen((BleState state) {   
 setState(() {    
  bleState = state; 
  if (bleState == BleState.On && !isScanning) { 
    startScanning();     }   }); });
super.initState();

**Comment by Giovanni-Fantin** [comment]
@rohitsangwan01 sorry man I have another question: i'd like to make the unpairing and the disconnection of the device when the app is closed. Is it possible? I've tried this:

 @override
  void dispose() async{
    _connectionStream?.cancel();
    _characteristicValueStream?.cancel();
    await unPair(device.address);
    await disconnect(device.address);
    super.dispose();
  }

but it's not working :(
