### ISSUE TITLE
subscribeToCharacteristic error

### ISSUE THREAD

**Issue by wpo778822** [rohitsangwan01/win_ble#4]
### I run example to get the following log,:

```
[✓] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.22000.675], locale zh-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
[✓] Android Studio (version 2021.1)

flutter: {_type: response, _id: null, result: null}
flutter: {_type: response, _id: 53, result: BluetoothLE#BluetoothLEbc:9a:78:56:34:12-11:f8:54:09:41:44}
flutter: {_type: response, _id: 54, result: [{0000180a-0000-1000-8000-00805f9b34fb}, {00001000-0000-1000-8000-00805f9b34fb}, {f000ffd0-0451-4000-b000-000000000000}]}
flutter: {_type: response, _id: 55, result: [{uuid: {00001001-0000-1000-8000-00805f9b34fb}, properties: {broadcast: false, read: true, writeWithoutResponse: true, write: true, notify: false, indicate: false, authenticatedSignedWrites: false, reliableWrite: false, writableAuxiliaries: false}}, {uuid: {00001002-0000-1000-8000-00805f9b34fb}, properties: {broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: true, indicate: false, authenticatedSignedWrites: false, reliableWrite: false, writableAuxiliaries: false}}, {uuid: {00001003-0000-1000-8000-00805f9b34fb}, properties: {broadcast: false, read: false, writeWithoutResponse: false, write: true, notify: false, indicate: false, authenticatedSignedWrites: false, reliableWrite: false, writableAuxiliaries: false}}, {uuid: {00001004-0000-1000-8000-00805f9b34fb}, properties: {broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, reliableWrite: false, writableAuxiliaries: false}}, {uuid: {00001005-0000-1000-8000-00805f9b34fb}, properties: {broadcast: false, read: true, writeWithoutResponse: false, write: true, notify: false, indicate: false, authenticatedSignedWrites: false, reliableWrite: false, writableAuxiliaries: false}}]}
flutter: {_type: response, _id: 56, error: æ æ³åå¥å±æ§ã



æ æ³åå¥å±æ§ã

}

```

PS:read/write is normal

**Comment by rohitsangwan01** [comment]
Can you confirm is Subscribing to that notification is possible
Can you share the characteristic uuid which is causing this issue

**Comment by wpo778822** [comment]
> @wpo778822 Can you confirm is Subscribing to that notification is possible
> Can you share the characteristic uuid which is causing this issue

sure,This bluetooth module I notify is 00001002-0000-1000-8000-00805F9B34FB.I found that the wrong UUID, such as passing in uppercase, would give me the correct feedback.

**Comment by rohitsangwan01** [comment]
@wpo778822 so you mean if you Subscribe to the same characteristic,but uuid in Upper case , then notification is working fine ?

**Comment by wpo778822** [comment]
> 

Sorry for the ambiguity, I mean deliberately passing in an error UUID will have the correct and readable error feedback.

**Comment by rohitsangwan01** [comment]
Seems like some issue in Decoding error message ,
you can try to download this Repo , and modify the example like you want 
also , in root folder , [lib/src/win_ble.dart](https://github.com/rohitsangwan01/win_ble/blob/main/lib/src/win_ble.dart) line : 53 , There you can print the Reponse without Parsing , and let me know what you get

**Comment by wpo778822** [comment]
> 

```
flutter: [93, 0, 0, 0, 123, 34, 95, 116, 121, 112, 101, 34, 58, 34, 114, 101, 115, 112, 111, 110, 115, 101, 34, 44, 34, 95, 105, 100, 34, 58, 52, 44, 34, 101, 114, 114, 111, 114, 34, 58, 34, 230, 151, 160, 230, 179, 149, 229, 134, 153, 229, 133, 165, 229, 177, 158, 230, 128, 167, 227, 128, 130, 92, 114, 92, 110, 92, 114, 92, 110, 230, 151, 160, 230, 179, 149, 229, 134, 153, 229, 133, 165, 229, 177, 158, 230, 128, 167, 227, 128, 130, 92, 114, 92, 110, 34, 125]
flutter: {_type: response, _id: 4, error: æ æ³åå¥å±æ§ã



æ æ³åå¥å±æ§ã

}
```

This is the original event that was thrown,I'm sorry I don't have the ability to run Windows program debugging, so that's all I can provide.

**Comment by rohitsangwan01** [comment]
@wpo778822 can you confirm with other Apps , like [Nrf Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp)
try if subscribing to this notification is working in App

**Comment by wpo778822** [comment]
> 
Android and iOS/macOS are normal,In my side has three different bluetooth devices, are stuck in subscribeToCharacteristic this step, my intention is to use Windows PC colleague convenient debugging, I have developed other platform.

**Comment by rohitsangwan01** [comment]
@wpo778822 can you try this pluin in another pc , or different ble Device with your PC , am not getting such error 
and hard to tell without debugging with the ble hardware
another option is to create a local gatt server by using nrfConnect app , and see if you are getting same error , 
and you can share those configs, i can try those for debugging
