### ISSUE TITLE
Detect bluetooth controller status

### ISSUE THREAD

**Issue by gtedone** [rohitsangwan01/win_ble#5]
First of all, a big thanks for this package: it made me immediately comfortable working with BLE on Windows.

Do you plan to add to this API somewhat to check the **status** of available BLE controller on the system (e.g. integrated BT interface, dongles, etc.)?

Thank you in advance and greetings for your great job!

**Comment by rohitsangwan01** [comment]
Thank you @gtedone  , i was planning to add an Api to check BleAvailability Status , which can tell if Bluetooth is Ready To use ,or maybe a Stream which can tell if bluetooth is PoweredOn/Off or if Adapter is available

**Comment by rohitsangwan01** [comment]
@gtedone just pushed an Update : V 0.0.5

To Get Bluetooth Status , Call
```dart
WinBle.bleState.listen((BleState state) {
    // Get BleState (On, Off, Unknown, Disabled, Unsupported)
});
```

**Comment by gtedone** [comment]
@rohitsangwan01 Thanks for your swift update, it works like a charm! 👍 

And sorry if I'm pushing you with another question: do you plan to add a `requestMtu` method too? 😏 

If you find more convenient, I will post my request in a separate issue thread.

**Comment by rohitsangwan01** [comment]
@gtedone yeah please add this as new issue

**Comment by gtedone** [comment]
Done [here] (https://github.com/rohitsangwan01/win_ble/issues/8).. (•‿•)
