### ISSUE TITLE
requestMtu implementation 

### ISSUE THREAD

**Issue by gtedone** [rohitsangwan01/win_ble#8]
As anticipated [here](https://github.com/rohitsangwan01/win_ble/issues/5#issuecomment-1177550261) , this is a request for implementing a `requestMtu` method, to negotiate the MTU on the adapter/system in use.

That would be great, and amongst other things, it can be useful for expanding the API and reach a **multiplatform support** (see also [here](https://github.com/rohitsangwan01/win_ble/issues/2) ).

**Comment by AlvaroOlivaresFlores** [comment]
Hi, I would also like this feature to be implemented since while working with IoT devices it becomes really handy.

**Comment by a136498491** [comment]
Seems the MTU can not be changed by user.
[https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattsession.maxpdusizechanged?view=winrt-22621](url)
> MaxPduSizeChanged is raised whenever the negotiated MTU for the Attribute Protocol (ATT) is changed. And that can be changed or negotiated by a remote Bluetooth peripheral. As a developer, you can't change the value used by Windows itself, since that's fully managed by the operating system.

**Comment by rohitsangwan01** [comment]
@AlvaroOlivaresFlores @gtedone like mentioned by @a136498491, seems like we cannot change [MtuSize](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattsession.maxpdusize?view=winrt-22621) on Windows , but we can get MaxMtu size, this api to get maxmtuSize is added in V1.0.0

**Comment by gtedone** [comment]
> we can get [MaxMtuSize](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattsession.maxpdusize?view=winrt-22621), this api to get maxmtuSize is added in V1.0.0

@rohitsangwan01. Thanks for confirming the issue and of course for the API update.

**Comment by acalpitojr** [comment]
I too have a ble peripheral that needs to have its MTU negotiated to 512.  By default the peripheral has a MTU of 23.  

I am able to negotiate an MTU of 512 using Android BLE applications.  Did I understand correctly, that Windows is incapable of negotiating MTU sizes with BLE peripheral devices?  This doesn't sound right to me.
